import type { MusicalTimeline } from "./types";

export const canonicalMusicalTimelineFixture: MusicalTimeline = {
  version: "picture-score:musical-ir:v1",
  duration: 4,
  bpm: 104,
  frames: [
    {
      time: 0,
      energy: 0.2,
      brightness: 0.35,
      density: 0.15,
      beatStrength: 0,
      melodyActivity: 0.25,
      ornamentActivity: 0.05,
      sustainLevel: 0.2,
      lowEnergy: 0.15,
      midEnergy: 0.25,
      highEnergy: 0.1,
    },
    {
      time: 2,
      energy: 0.65,
      brightness: 0.7,
      density: 0.55,
      beatStrength: 0.8,
      melodyActivity: 0.75,
      ornamentActivity: 0.5,
      sustainLevel: 0.6,
      lowEnergy: 0.5,
      midEnergy: 0.7,
      highEnergy: 0.6,
    },
  ],
  events: [
    {
      id: "section-0",
      type: "section",
      time: 0,
      strength: 0.2,
      index: 0,
      confidence: 1,
      energyDelta: 0,
    },
    {
      id: "rhythm-1",
      type: "rhythm",
      time: 1,
      strength: 0.8,
      subdivision: 4,
    },
    {
      id: "harmony-1",
      type: "harmony",
      time: 1,
      strength: 0.7,
      tension: 0.35,
      changeAmount: 0.75,
      root: 0,
      quality: "major",
    },
    {
      id: "melody-1",
      type: "melody",
      time: 1,
      strength: 0.65,
      pitch: 67,
      normalizedPitch: 0.72,
      duration: 0.5,
      direction: "up",
    },
    {
      id: "ornament-1",
      type: "ornament",
      time: 1.5,
      strength: 0.55,
      brightness: 0.9,
      complexity: 0.45,
    },
    {
      id: "resonance-1",
      type: "resonance",
      time: 2.5,
      strength: 0.6,
      duration: 1.25,
      depth: 0.8,
    },
  ],
  metadata: {
    analysisVersion: "fixture-v1",
  },
};
