import { afterEach, expect, it, vi } from 'vitest';
import { GardenTransport } from '../garden/gardenTransport';
import { emptyGarden, makeObject } from '../garden/gardenState';
import { emptyProject } from '../music/project';
vi.mock('../music/audio', () => ({outputBus:()=>({}),voice:()=>[]}));
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
it('enters and dissolves spatial phrases without restarting the running audio clock',async()=>{
  vi.useFakeTimers();vi.stubGlobal('document',{hidden:false});
  const param=()=>({value:0,setTargetAtTime(value:number){this.value=value;},cancelScheduledValues(){}});
  const ctx={currentTime:0,state:'running',resume:async()=>{},createGain:()=>({gain:param(),connect(){},disconnect(){}})};
  vi.stubGlobal('AudioContext',class {constructor(){return ctx;}});
  const project={...emptyProject(),strokes:[{id:'line',points:[{x:100,y:300,pressure:.5,time:0},{x:500,y:100,pressure:.5,time:1}]}]};
  const state={...emptyGarden(),bpm:60,listener:{x:.5,y:.5},objects:[.3,.5,.7].map((x,i)=>makeObject(project,{x,y:.45},'o'+i))};
  const engine=new GardenTransport();
  await engine.start(state);
  const schedule=()=> (engine as unknown as {schedule:()=>void}).schedule();
  ctx.currentTime=.3;schedule();ctx.currentTime=1.2;schedule();
  expect(engine.wonder[0]?.rule).toBe('garden-lineup-cascade');
  expect(engine.plan?.objectPlans.get('o0')?.wonder).toContain('garden-lineup-cascade');
  const before=engine.beat;
  const moved={...state,objects:state.objects.map((o,i)=>i===1?{...o,world:{...o.world,y:.7}}:o)};
  engine.update(moved);expect(engine.beat).toBe(before);
  ctx.currentTime=1.3;schedule();ctx.currentTime=1.6;schedule();ctx.currentTime=2.2;schedule();
  expect(engine.running).toBe(true);expect(engine.beat).toBeCloseTo(before+1);
  expect(engine.wonder.some(e=>e.rule==='garden-lineup-cascade')).toBe(false);
  engine.update(state);ctx.currentTime=2.3;schedule();ctx.currentTime=2.6;schedule();ctx.currentTime=3.2;schedule();
  expect(engine.wonder[0]?.rule).toBe('garden-lineup-cascade');
  expect(engine.beat).toBeCloseTo(before+2);engine.stop();
});
