import { afterEach, expect, it, vi } from 'vitest';
import { GardenTransport } from './gardenTransport';
import { emptyGarden, makeObject } from './gardenState';
import { emptyProject } from '../music/project';
import { voice } from '../music/audio';
import type { GardenLifeBridge, GardenLifeEvent } from './life';
vi.mock('../music/audio',()=>({outputBus:()=>({}),voice:vi.fn(()=>Array.from({length:3},()=>({addEventListener(){},stop(){}})))}));
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.clearAllMocks();});
it('observes one audible chord at the audio onset, not one event per oscillator, and stops pending UI work',async()=>{
  vi.useFakeTimers();vi.stubGlobal('document',{hidden:false});
  const param=()=>({value:0,setTargetAtTime(value:number){this.value=value;},cancelScheduledValues(){}});
  const ctx={currentTime:0,state:'running',resume:async()=>{},createGain:()=>({gain:param(),connect(){},disconnect(){}})};
  vi.stubGlobal('AudioContext',class {constructor(){return ctx;}});
  const project={...emptyProject(),strokes:[{id:'chord',points:[{x:500,y:20,time:0,pressure:.5},{x:500,y:390,time:1,pressure:.5}]}]};
  const state={...emptyGarden(),objects:[makeObject(project,{x:.5,y:.5},'a')],listener:{x:.5,y:.5}};
  const engine=new GardenTransport(), heard:(GardenLifeEvent|null)[]=[];
  engine.onLifeEvent=e=>heard.push(e);
  await engine.start(state);
  expect(voice).toHaveBeenCalled();
  expect(heard.filter(Boolean)).toHaveLength(0);
  ctx.currentTime=.075;vi.advanceTimersByTime(16);
  const attacks=heard.filter((e):e is GardenLifeEvent=>!!e && e.type!=='relation');
  expect(attacks).toHaveLength(1);
  expect(attacks[0]).toMatchObject({objectId:'a',role:'harmony',at:.06,source:{strokeId:'chord'}});
  expect(vi.mocked(voice).mock.calls.length*3).toBeGreaterThan(attacks.length);
  const beat=engine.beat;engine.update({...state,listener:{x:.55,y:.5}});expect(engine.beat).toBe(beat);
  engine.stop();
  expect((engine as unknown as {life:GardenLifeBridge}).life.pendingCount).toBe(0);
  expect(heard.at(-1)).toBeNull();expect(vi.getTimerCount()).toBe(0);
});
